// generated by ai
// Simple test runner for pre-push hook

const assert = require('assert');

// Test suite
function runTests() {
  const tests = [];
  let passed = 0;
  let failed = 0;

  // Helper to register tests
  function test(name, fn) {
    tests.push({ name, fn });
  }

  // Example test - replace with your actual tests
  test('Basic assertion test', () => {
    assert.strictEqual(1 + 1, 2, 'Math should work');
  });

  test('String test', () => {
    assert.strictEqual('hello', 'hello', 'Strings should match');
  });

  // Run all tests
  console.log('\n🧪 Running tests...\n');
  
  for (const { name, fn } of tests) {
    try {
      fn();
      console.log(`✅ ${name}`);
      passed++;
    } catch (error) {
      console.error(`❌ ${name}`);
      console.error(`   Error: ${error.message}`);
      failed++;
    }
  }

  // Summary
  console.log(`\n📊 Test Results: ${passed} passed, ${failed} failed\n`);

  if (failed > 0) {
    process.exit(1);
  }
  
  return failed === 0;
}

// Run tests if executed directly
if (require.main === module) {
  runTests();
}

module.exports = { runTests };
