const bcrypt = require('bcrypt');
const jwt = require('jsonwebtoken');

// In-memory user store (for demo purposes)
const users = [];

// Secret key for JWT (in production, use environment variable)
const JWT_SECRET = 'your-secret-key-change-in-production';

/**
 * Register a new user
 * @param {string} username - User's username
 * @param {string} password - User's password
 * @returns {Promise<Object>} User object without password
 */
async function signup(username, password) {
  // Check if user already exists
  const existingUser = users.find(u => u.username === username);
  if (existingUser) {
    throw new Error('Username already exists');
  }

  // Hash password
  const saltRounds = 10;
  const hashedPassword = await bcrypt.hash(password, saltRounds);

  // Create user
  const user = {
    id: users.length + 1,
    username,
    password: hashedPassword,
    createdAt: new Date().toISOString()
  };

  users.push(user);

  // Return user without password
  const { password: _, ...userWithoutPassword } = user;
  return userWithoutPassword;
}

/**
 * Login user and return JWT token
 * @param {string} username - User's username
 * @param {string} password - User's password
 * @returns {Promise<Object>} Token and user info
 */
async function login(username, password) {
  // Find user
  const user = users.find(u => u.username === username);
  if (!user) {
    throw new Error('Invalid username or password');
  }

  // Verify password
  const isValidPassword = await bcrypt.compare(password, user.password);
  if (!isValidPassword) {
    throw new Error('Invalid username or password');
  }

  // Generate JWT token
  const token = jwt.sign(
    { userId: user.id, username: user.username },
    JWT_SECRET,
    { expiresIn: '24h' }
  );

  // Return token and user info
  const { password: _, ...userWithoutPassword } = user;
  return {
    token,
    user: userWithoutPassword
  };
}

/**
 * Verify JWT token
 * @param {string} token - JWT token
 * @returns {Object} Decoded token payload
 */
function verifyToken(token) {
  try {
    const decoded = jwt.verify(token, JWT_SECRET);
    return decoded;
  } catch (error) {
    throw new Error('Invalid or expired token');
  }
}

/**
 * Get user by ID
 * @param {number} userId - User ID
 * @returns {Object|null} User object without password
 */
function getUserById(userId) {
  const user = users.find(u => u.id === userId);
  if (!user) {
    return null;
  }
  const { password: _, ...userWithoutPassword } = user;
  return userWithoutPassword;
}

module.exports = {
  signup,
  login,
  verifyToken,
  getUserById
};

// generated by ai
